// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace pharma_quick_test2.Models
{
    public partial class ActiveIngredient
    {
        public ActiveIngredient()
        {
            MedicationActiveIngredients = new HashSet<MedicationActiveIngredient>();
        }

        [Key]
        [Column("IngredientID")]
        public int IngredientId { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string IngredientName { get; set; }

        [InverseProperty("Ingredient")]
        public virtual ICollection<MedicationActiveIngredient> MedicationActiveIngredients { get; set; }
    }
}