// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace pharma_quick_test2.Models
{
    public partial class MedicationReplacement
    {
        [Key]
        [Column("medId")]
        public int MedId { get; set; }
        [Key]
        [Column("replacementId")]
        public int ReplacementId { get; set; }

        [ForeignKey("MedId")]
        [InverseProperty("MedicationReplacementMeds")]
        public virtual Medication Med { get; set; }
        [ForeignKey("ReplacementId")]
        [InverseProperty("MedicationReplacementReplacements")]
        public virtual Medication Replacement { get; set; }
    }
}