// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace pharma_quick_test2.Models
{
    public partial class Medication
    {
        public Medication()
        {
            MedicationActiveIngredients = new HashSet<MedicationActiveIngredient>();
            MedicationReplacementMeds = new HashSet<MedicationReplacement>();
            MedicationReplacementReplacements = new HashSet<MedicationReplacement>();
        }

        [Key]
        [Column("MedicationID")]
        public int MedicationId { get; set; }
        public string MedicationName { get; set; }
        public string UseOfMedications { get; set; }
        public string ContraindicationsForUse { get; set; }
        public string Precautions { get; set; }
        public string SideEffects { get; set; }
        [Column("CategoryID")]
        public int? CategoryId { get; set; }

        [ForeignKey("CategoryId")]
        [InverseProperty("Medications")]
        public virtual MedicationCategory Category { get; set; }
        [InverseProperty("Medication")]
        public virtual ICollection<MedicationActiveIngredient> MedicationActiveIngredients { get; set; }
        [InverseProperty("Med")]
        public virtual ICollection<MedicationReplacement> MedicationReplacementMeds { get; set; }
        [InverseProperty("Replacement")]
        public virtual ICollection<MedicationReplacement> MedicationReplacementReplacements { get; set; }
    }
}