// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace pharma_quick_test2.Models
{
    [Index("IngredientId", Name = "IX_MedicationActiveIngredients_IngredientID")]
    public partial class MedicationActiveIngredient
    {
        [Key]
        [Column("MedicationID")]
        public int MedicationId { get; set; }
        [Key]
        [Column("IngredientID")]
        public int IngredientId { get; set; }

        [ForeignKey("IngredientId")]
        [InverseProperty("MedicationActiveIngredients")]
        public virtual ActiveIngredient Ingredient { get; set; }
        [ForeignKey("MedicationId")]
        [InverseProperty("MedicationActiveIngredients")]
        public virtual Medication Medication { get; set; }
    }
}