// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace pharma_quick_test2.Models
{
    public partial class pharma_Context : DbContext
    {
        public pharma_Context()
        {
        }

        public pharma_Context(DbContextOptions<pharma_Context> options)
            : base(options)
        {
        }

        public virtual DbSet<ActiveIngredient> ActiveIngredients { get; set; }
        public virtual DbSet<Medication> Medications { get; set; }
        public virtual DbSet<MedicationActiveIngredient> MedicationActiveIngredients { get; set; }
        public virtual DbSet<MedicationCategory> MedicationCategories { get; set; }
        public virtual DbSet<MedicationReplacement> MedicationReplacements { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ActiveIngredient>(entity =>
            {
                entity.HasKey(e => e.IngredientId)
                    .HasName("PK__ActiveIn__BEAEB27AA35F184D");

                entity.Property(e => e.IngredientId).ValueGeneratedNever();
            });

            modelBuilder.Entity<Medication>(entity =>
            {
                entity.Property(e => e.MedicationId).ValueGeneratedNever();

                entity.HasOne(d => d.Category)
                    .WithMany(p => p.Medications)
                    .HasForeignKey(d => d.CategoryId)
                    .HasConstraintName("FK__Medicatio__Categ__267ABA7A");
            });

            modelBuilder.Entity<MedicationActiveIngredient>(entity =>
            {
                entity.HasKey(e => new { e.MedicationId, e.IngredientId })
                    .HasName("PK__Medicati__D906F1FDC044A754");

                entity.HasOne(d => d.Ingredient)
                    .WithMany(p => p.MedicationActiveIngredients)
                    .HasForeignKey(d => d.IngredientId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Medicatio__Ingre__2C3393D0");

                entity.HasOne(d => d.Medication)
                    .WithMany(p => p.MedicationActiveIngredients)
                    .HasForeignKey(d => d.MedicationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Medicatio__Medic__2B3F6F97");
            });

            modelBuilder.Entity<MedicationCategory>(entity =>
            {
                entity.HasKey(e => e.CategoryId)
                    .HasName("PK__Medicati__19093A2BC6D087EB");

                entity.Property(e => e.CategoryId).ValueGeneratedNever();
            });

            modelBuilder.Entity<MedicationReplacement>(entity =>
            {
                entity.HasKey(e => new { e.MedId, e.ReplacementId })
                    .HasName("PK__Medicati__5A96AEE443919F42");

                entity.HasOne(d => d.Med)
                    .WithMany(p => p.MedicationReplacementMeds)
                    .HasForeignKey(d => d.MedId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Medicatio__medId__6477ECF3");

                entity.HasOne(d => d.Replacement)
                    .WithMany(p => p.MedicationReplacementReplacements)
                    .HasForeignKey(d => d.ReplacementId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Medicatio__repla__656C112C");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}